### ISSUE TITLE
Can't access Buckets

### ISSUE THREAD

**Issue by arispujud** [Unitech/keymetrics.io#256]
I got this error when accessing my Bucket and I can't create a new bucket.

Error
Failed to load the page. Please retry later.

But when I login with another account, I can access bucket on my second account. So what happens in my fist account?

**Comment by arispujud** [comment]
This is the errors when I open inspect element

```
Failed to load resource: net::ERR_FAILED
createError.js:16 Uncaught (in promise) Error: Network Error
    at e.exports (createError.js:16)
    at XMLHttpRequest.f.onerror (xhr.js:83)
app.pm2.io/:1 Access to XMLHttpRequest at 'https://diavel.keymetrics.io/api/bucket/5e38f365c78945afe738a5/users_authorized' from origin 'https://app.pm2.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
pm2Io.js:64 Unexpected pm2-js-api error: Error: Network Error
    at e.exports (createError.js:16)
    at XMLHttpRequest.f.onerror (xhr.js:83)
(anonymous) @ pm2Io.js:64
diavel.keymetrics.io/api/bucket/5e38f365c78945afe738a5/users_authorized:1 Failed to load resource: net::ERR_FAILED
```

**Comment by 0xae** [comment]
Confirmed here. Cant acess buckets too for 2 days now.

**Comment by 0xae** [comment]
In My case, its giving a 502 - Bad Gateway

**Comment by SharpBCD** [comment]
Same here.
CORS error.
![pm2 errors](https://user-images.githubusercontent.com/31144210/92390957-86bef680-f124-11ea-8e3d-e8e766a7b6f7.png)

**Comment by SimoneDesantisAltravia** [comment]
Same for me.
![Screenshot_20200907_181819](https://user-images.githubusercontent.com/67371387/92405735-8e879680-f136-11ea-83c7-333373f055d7.png)

**Comment by luisjuniorj** [comment]
Same

**Comment by akosasante** [comment]
Same here for the last couple of days. Please fix; or let us know if there's any further info we should provide!

Here is the failed responses I'm getting: `https://diavel.keymetrics.io/api/bucket/5e42ce224052fb775d1da15c/users_authorized` 

GET call to that endpoint: `net::ERR_FAILED` 
OPTIONS call to that endpoint: `502 Bad Gateway` 

It doesn't look like the request is sending any cookies; there is a `Bearer` auth token in the header of the request. Everything else looks normal enough; maybe CORS issues or something?

**Comment by gencero** [comment]
I've been getting the same error, for a few days. Please fix this or tell us a solution.

**Comment by VanderDT** [comment]
Error
Failed to load the page. Please retry later.

**Comment by nicolab28** [comment]
Same error

**Comment by luisjuniorj** [comment]
They are going out of busines, has anyone have some replacement? paid or free?

**Comment by Unitech** [comment]
This is fixed, our free data node had 300+ days up time with some petabytes of data transferred... I just switched the whole free data to another node, it works like a charm now 
![Screenshot from 2020-09-08 17-40-49](https://user-images.githubusercontent.com/757747/92498182-9c065480-f1fa-11ea-826f-03fc54c9d0a0.png)

**Comment by Unitech** [comment]
We deliver the best we can for our dear free user, hopefully we are not running our servers on AWS else we would be bankrupt.

**Comment by 0xae** [comment]
Hi there @Unitech thanks. can confirm, the service is back now.
Will definitely upgrade soon.

**Comment by gencero** [comment]
A few minutes ago I am getting the same error again.

**Comment by SharpBCD** [comment]
Damn it, I refreshed the browser because @gencero said it's not working again and, indeed, it is not. 
Same error again. Guys, do you need help with nginx? or something? Do let us know, we'll try to help.

@luisjuniorj  say what?! :-O

**Comment by elpaxel** [comment]
Yeah diavel.keymetrics.io is down or something.

**Comment by Pho3niX90** [comment]
Same issue this side, bucket in RSA giving this error, bucket in US working. 
![image](https://user-images.githubusercontent.com/7858187/94000878-0ccf7400-fd98-11ea-888c-304e34b375b4.png)

**Comment by elpaxel** [comment]
@Unitech I mention you because it is like 2 days already and issue not resolved.
If you need money on server for free users make $5-10 tiers please with reduced functionality or something.
Because $40 for developers like me is like 1\3 of my revenue from side project.

**Comment by 0xae** [comment]
@elpaxi I agree with you, that price tag is difficult if not unfeasible.
As a free user i have no right to complain and i must confess that the service works great when it's supposed too. 

This is the second time this month, and with the lack of feedback, i'm convinced they no longer care about us free users, no other choice but to fork the open-source version and spin up a micro aws instance.

**Comment by SharpBCD** [comment]
Still nothing...
time to think about alternatives, like @elpaxel  said?

**Comment by azbaron** [comment]
Can't access mine either. Really frustrating when you don't see any "status updates" on the issue(s) anywhere.

**Comment by galipmedia** [comment]
I was relying heavily on this to deliver logs. I am in development. I second the idea of having a smaller paid option, even if its what we get for free but it just works.

**Comment by GalaxySH** [comment]
Same issues here, tried logging out and logging back in to terminal before reading GitHub, now I can't log back in. Time to go back to forever js for now.

I also cannot create new buckets, of course.

Edit: And now it works again, I had to log in to the website again, I guess. But I had to do this with a new bucket, the old bucket is still not accessible.

**Comment by ppdolla** [comment]
Same issues here. 
![image](https://user-images.githubusercontent.com/71992166/94379844-d3b74b00-016d-11eb-9612-a4c262aa5bd6.png)

**Comment by gencero** [comment]
it is fixed. i can access the buckets now.

**Comment by azbaron** [comment]
> it is fixed. i can access the buckets now.

Yep, I'm also able to access my buckets now. Will still err on the side of caution with depending on this so heavily.

**Comment by christopheSeeka** [comment]
Not fixed for me, started again this morning:

![pm2-error](https://user-images.githubusercontent.com/50763365/94642152-f2584600-0315-11eb-80fc-fb2f635a0389.jpg)

**Comment by sawa-ko** [comment]
Same error.

**Comment by ghost** [comment]
can not access our bucket now, either (5f3a65df0c075861b33118f4) - and now it works again - thx to whoever did something :)

**Comment by GalaxySH** [comment]
@arispujud can this issue be closed? I am able to access my bucket now.

**Comment by lukeescude** [comment]
This appears to be happening to me right now - Failed to load the page. I'll try and login later, maybe they're having an outage.

**Comment by SharpBCD** [comment]
Yeap It's back

**Comment by ghost** [comment]
same here
Access to XMLHttpRequest at 'https://renegade.keymetrics.io/api/bucket/XXXX/users_authorized' from origin 'https://app.pm2.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Floffah** [comment]
yep happening here too

**Comment by TimPasquini** [comment]
I am having this issue. Browser console shows ERR_CONNECTION_REFUSED for zodiac.keymetrics.io

**Comment by hypo-thesis** [comment]
Today this issue is still present. It's amazing how a 2 year old issue hasn't been addressed yet.

**Comment by TimPasquini** [comment]
@hypo-thesis When I had this issue it was addressed within a day or two of reporting it.

**Comment by erencelik** [comment]
![image](https://user-images.githubusercontent.com/6137678/208095299-fc894bcd-cf4c-40d9-b139-ca7da62b7f97.png)

Can't access either.

P.S: After digging into few hours (a huge lack of documentation) it appears that Web Interface is not included in free plan.

**Comment by alexpaluzzi** [comment]
This is back again... all week so far at least. Even for my paid buckets.

**Comment by adil-uk** [comment]
> This is back again... all week so far at least. Even for my paid buckets.

I am also experiencing the same issue. - it's very annoying!

**Comment by matrndev** [comment]
I was able to get it working by logging into pm2.io, creating a new bucket there and then linking my sever using `pm2 link <publickey> <privatekey>`. It doesn't work using `pm2 monitor`.

**Comment by hypo-thesis** [comment]
same issue

**Comment by mirac** [comment]
I have the same problem

**Comment by AhmedHammad-klar** [comment]
I have the same problem, any way to address it?

**Comment by iulianhlc** [comment]
Error
Failed to load the page. Please retry later.

Whats going on>?

**Comment by yuuk** [comment]
any solutions update?

**Comment by dyarkovoy** [comment]
Same problem here
![image](https://github.com/user-attachments/assets/8590c3d7-9410-4628-8792-401c0860a581)
